### ISSUE TITLE
makefile suggestions

### ISSUE THREAD

**Issue by sagiegurari** [althonos/pruefung#1]
cargo-make is really new so trying to help adoption of it and got few suggestions that might help a bit.
None of them are a must, but could improve things a bit.

* tasks.audit - your task is exactly the same as in the default.toml, so I think you can remove your declaration. tasks defined in default.toml are automatically available so you can use it without redefining it.
This would help keep your makefile small and simple.
* tasks.coverage looks like tasks.coverage-tarpaulin so you can just put an alias 

````toml
[tasks.coverage]
alias = "tasks.coverage-tarpaulin"
````
instead of redefining the task.

* travis cache for cargo-make should be disabled otherwise you are not getting new task definitions and new features.
For example with the version you are running, you are missing tasks.coverage-tarpaulin.
You could keep the cache but always install cargo-make using the cargo install --force flag so the cache will be kept for other rust crates that are used.

* you can merge multiple calls to cargo make to a single call.
for example you have

````yaml
  - cargo make audit
  - cargo make chandler
````

But you can define a task that has dependencies to both of these (letscall it after_script),

````toml
[tasks.after_script]
dependencies = ["audit", "chandler"]
````

and than just call: cargo make after_script.
this would help make your travis yml smaller and allow you to call that flow manually from your dev machine with a single command.

**Comment by althonos** [comment]
@sagiegurari : thanks for this review and for the tool itself ! 

* For the *tarpaulin* task, I started using `cargo-make` before it was added to the default Makefile, so now I can remove it :)
* I prefer to have the steps separately in the `.travis.yml`, to avoid going back and forth between the Makefile and the Travis file whenever I want to check a task definition.

For the cache, at the moment I prefer to reset it manually when a new version is published, at the time it takes to build `cargo-make` is incredibly long compared to my actual crate (which only has 5 transitive dependencies in total). See sagiegurari/cargo-make#4 about an enhancement proposal ;)
